# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/system_with_simple_alu/system_with_simple_alu.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_with_simple_alu || ORIG_REF_NAME==system_with_simple_alu} -quiet] -quiet

# IP: bd/system_with_simple_alu/ip/system_with_simple_alu_processing_system7_0_0/system_with_simple_alu_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_with_simple_alu_processing_system7_0_0 || ORIG_REF_NAME==system_with_simple_alu_processing_system7_0_0} -quiet] -quiet

# IP: bd/system_with_simple_alu/ip/system_with_simple_alu_ps7_0_axi_periph_0/system_with_simple_alu_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_with_simple_alu_ps7_0_axi_periph_0 || ORIG_REF_NAME==system_with_simple_alu_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/system_with_simple_alu/ip/system_with_simple_alu_rst_ps7_0_100M_0/system_with_simple_alu_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_with_simple_alu_rst_ps7_0_100M_0 || ORIG_REF_NAME==system_with_simple_alu_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/system_with_simple_alu/ip/system_with_simple_alu_simple_alu_0_1/system_with_simple_alu_simple_alu_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_with_simple_alu_simple_alu_0_1 || ORIG_REF_NAME==system_with_simple_alu_simple_alu_0_1} -quiet] -quiet

# IP: bd/system_with_simple_alu/ip/system_with_simple_alu_auto_pc_0/system_with_simple_alu_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_with_simple_alu_auto_pc_0 || ORIG_REF_NAME==system_with_simple_alu_auto_pc_0} -quiet] -quiet

# XDC: /home/cristian/Documents/ACES/RC/assignment-2/assignment-2.gen/sources_1/bd/system_with_simple_alu/system_with_simple_alu_ooc.xdc
