# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/NexysA7.xdc

# Block Designs: bd/uart_rx_design/uart_rx_design.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uart_rx_design || ORIG_REF_NAME==uart_rx_design} -quiet] -quiet

# IP: bd/uart_rx_design/ip/uart_rx_design_clk_wiz_0_0/uart_rx_design_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uart_rx_design_clk_wiz_0_0 || ORIG_REF_NAME==uart_rx_design_clk_wiz_0_0} -quiet] -quiet

# IP: bd/uart_rx_design/ip/uart_rx_design_led_ctrl_0_0/uart_rx_design_led_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uart_rx_design_led_ctrl_0_0 || ORIG_REF_NAME==uart_rx_design_led_ctrl_0_0} -quiet] -quiet

# IP: bd/uart_rx_design/ip/uart_rx_design_uart_receiver_0_0/uart_rx_design_uart_receiver_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==uart_rx_design_uart_receiver_0_0 || ORIG_REF_NAME==uart_rx_design_uart_receiver_0_0} -quiet] -quiet

# XDC: /home/cristian/Documents/ACES/RC/assignment-1/assignment-1.gen/sources_1/bd/uart_rx_design/uart_rx_design_ooc.xdc
