# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/linear_contrast_stretching/linear_contrast_stretching.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==linear_contrast_stretching || ORIG_REF_NAME==linear_contrast_stretching} -quiet] -quiet

# IP: bd/linear_contrast_stretching/ip/linear_contrast_stretching_processing_system7_0_1/linear_contrast_stretching_processing_system7_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==linear_contrast_stretching_processing_system7_0_1 || ORIG_REF_NAME==linear_contrast_stretching_processing_system7_0_1} -quiet] -quiet

# IP: bd/linear_contrast_stretching/ip/linear_contrast_stretching_ps7_0_axi_periph_1/linear_contrast_stretching_ps7_0_axi_periph_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==linear_contrast_stretching_ps7_0_axi_periph_1 || ORIG_REF_NAME==linear_contrast_stretching_ps7_0_axi_periph_1} -quiet] -quiet

# IP: bd/linear_contrast_stretching/ip/linear_contrast_stretching_rst_ps7_0_100M_1/linear_contrast_stretching_rst_ps7_0_100M_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==linear_contrast_stretching_rst_ps7_0_100M_1 || ORIG_REF_NAME==linear_contrast_stretching_rst_ps7_0_100M_1} -quiet] -quiet

# IP: bd/linear_contrast_stretching/ip/linear_contrast_stretching_xbar_0/linear_contrast_stretching_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==linear_contrast_stretching_xbar_0 || ORIG_REF_NAME==linear_contrast_stretching_xbar_0} -quiet] -quiet

# IP: bd/linear_contrast_stretching/ip/linear_contrast_stretching_axi_mem_intercon_0/linear_contrast_stretching_axi_mem_intercon_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==linear_contrast_stretching_axi_mem_intercon_0 || ORIG_REF_NAME==linear_contrast_stretching_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/linear_contrast_stretching/ip/linear_contrast_stretching_LinearContrastStretc_0_2/linear_contrast_stretching_LinearContrastStretc_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==linear_contrast_stretching_LinearContrastStretc_0_2 || ORIG_REF_NAME==linear_contrast_stretching_LinearContrastStretc_0_2} -quiet] -quiet

# IP: bd/linear_contrast_stretching/ip/linear_contrast_stretching_auto_pc_0/linear_contrast_stretching_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==linear_contrast_stretching_auto_pc_0 || ORIG_REF_NAME==linear_contrast_stretching_auto_pc_0} -quiet] -quiet

# IP: bd/linear_contrast_stretching/ip/linear_contrast_stretching_auto_pc_1/linear_contrast_stretching_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==linear_contrast_stretching_auto_pc_1 || ORIG_REF_NAME==linear_contrast_stretching_auto_pc_1} -quiet] -quiet

# XDC: /home/cristian/Documents/ACES/RC/assignment-3/vivado/linear_contrast_stretching.gen/sources_1/bd/linear_contrast_stretching/linear_contrast_stretching_ooc.xdc
