# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/cristian/Documents/ACES/RC/assignment-2/assignment-2.srcs/sources_1/bd/system_with_simple_alu/ip/system_with_simple_alu_processing_system7_0_0/system_with_simple_alu_processing_system7_0_0.xci
# IP: The module: 'system_with_simple_alu_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/cristian/Documents/ACES/RC/assignment-2/assignment-2.gen/sources_1/bd/system_with_simple_alu/ip/system_with_simple_alu_processing_system7_0_0/system_with_simple_alu_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_with_simple_alu_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/cristian/Documents/ACES/RC/assignment-2/assignment-2.srcs/sources_1/bd/system_with_simple_alu/ip/system_with_simple_alu_processing_system7_0_0/system_with_simple_alu_processing_system7_0_0.xci
# IP: The module: 'system_with_simple_alu_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/cristian/Documents/ACES/RC/assignment-2/assignment-2.gen/sources_1/bd/system_with_simple_alu/ip/system_with_simple_alu_processing_system7_0_0/system_with_simple_alu_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_with_simple_alu_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
